# **MÓDULO 20 - Projeto de Credit Score - Naive Bayes**

No módulo 17 vocês realizaram a primeira etapa do projeto de crédito de vocês.
Então fizeram o tratamendo dos dados, balancearam as classes, transformaram as variáveis categóricas e separam base de treino e teste.
Nessa aula aplicaremos o algoritmo de naive bayes a base de vocês afim de tentarmos trazer previsões do score de crédito.

**IMPORTANTE:** Não se esqueçam de ao enviar o código de vocês para os tutores, enviarem as bases, pois como cada um de vocês realizou as alterações de tratamento indidualmente o tutor precisa ter acesso aos seus dados individuais.

In [26]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.figure_factory as ff
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score

Durante a aula nossa variável a ser prevista (churn) continha apenas 2 categorias, a base de vocês contém mais. O Naive Bayes pode ser aplicado para problemas de classificação com múltiplas classes da mesma forma que para problemas de classificação binária. O Naive Bayes é um algoritmo de classificação probabilístico que calcula a probabilidade de uma amostra pertencer a cada classe e seleciona a classe com a maior probabilidade como a previsão final.
Em resumo, o Naive Bayes pode ser aplicado da mesma maneira para problemas de classificação com múltiplas classes, e os mesmos princípios se aplicam em termos de treinamento, avaliação e aplicação do modelo.

# 1) Comece carregando as bases de treino (X e y) e teste (X e y).
Verifique se o número de linhas condiz, se as variáveis estão corretas sendo apenas a de score para y e as demais nas bases de X e por último, se Y está balanceada no teste.

In [5]:
x_train = pd.read_csv('Dados/01. x_train_balanced.csv')
x_test = pd.read_csv('Dados/03. x_test.csv')
y_train = pd.read_csv('Dados/02. y_train_balanced.csv')
y_test = pd.read_csv('Dados/04. y_test.csv')

In [6]:
x_train

,Age,Income,Number of Children,Gender_Encoded,Marital_Status_Encoded,Home_Ownership_Encoded,Education_Encoded
0,26,45000.000000,0,0,1,1,1.000000
1,29,27500.000000,0,0,1,1,0.000000
2,25,62500.000000,0,0,1,1,2.000000
3,29,68000.000000,2,0,0,0,4.000000
4,31,65000.000000,0,1,1,1,2.000000
...,...,...,...,...,...,...,...
247,29,43703.466973,0,0,1,1,1.000000
248,34,47500.000000,0,1,1,1,1.000000
249,29,57500.000000,0,0,1,1,1.572459
250,25,60063.547817,0,0,1,1,2.000000
251,33,52500.000000,0,1,1,1,0.000000

In [7]:
y_train

     Credit_Score_Encoded
0                     1.0
1                     0.0
2                     1.0
3                     1.0
4                     1.0
..                    ...
247                   1.0
248                   1.0
249                   1.0
250                   1.0
251                   1.0

[252 rows x 1 columns]

In [18]:
x_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     41 non-null     int64
 1   Income                  41 non-null     float64
 2   Number of Children      41 non-null     int64
 3   Gender_Encoded          41 non-null     int64
 4   Marital_Status_Encoded  41 non-null     int64
 5   Home_Ownership_Encoded  41 non-null     int64
 6   Education_Encoded       41 non-null     float64
dtypes: float64(2), int64(5)
memory usage: 2.4 KB

In [19]:
y_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Credit_Score_Encoded  41 non-null     float64
dtypes: float64(1)
memory usage: 460.0 bytes

Y é Score de Crédito e número de linhas ok entre as bases de Treino e Teste

Score de Crédito

- 0 ---> Low
- 1 ---> Average
- 2 ---> High

# 2) Aplique o algoritmo de Naive Bayes aos dados de treinamento.

In [20]:
# Instância do Classificador
naive_credit_score = GaussianNB()

# Treinamento do Modelo
naive_credit_score.fit(x_train, y_train)

C:\Users\leobo\PycharmProjects\Conteudos_Gerais_Data_Science_EBAC\.venv\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

# 3) Faça a avaliação do modelo com os dados de treinamento.
Traga a acurácia, recall e plote a matriz de confusão. Não se esqueça de avaliar com suas palavras o desempenho do modelo, interpretando as métricas.

Dica: Para calcularmos o recall em classificação multi classe precisamos usar o atributo macro:
recall = recall_score(y_train, y_pred_train, average='macro')

In [25]:
# Fazendo previsões nos dados de Treino
y_pred_train = naive_credit_score.predict(x_train)

# ACURÁCIA
train_accuracy = accuracy_score(y_train, y_pred_train)
print("Acurácia:", train_accuracy)

# RECALL
train_recall = recall_score(y_train, y_pred_train, average = 'macro')
print("Recall:", train_recall)

Acurácia: 0.9801587301587301
Recall: 0.9801587301587302

In [34]:
# Matriz de Confusão
conf_matrix = confusion_matrix(y_train, y_pred_train)

# Definindo os nomes de classes
class_names = ['Low', 'Average', 'High']

# Matriz de Confusão
fig = ff.create_annotated_heatmap(
    z = conf_matrix,
    x = class_names,
    y = class_names,
    colorscale = 'Blues',
    showscale = True
)

# Estilizando
fig.update_layout(
    title = 'Matriz de Confusão',
    xaxis_title = 'Rótulos Previstos',
    yaxis_title = 'Rótulos Verdadeiros',
    font = dict(
        family = 'Arial',
        size = 12,
        color = 'black'
    ),
    template = 'plotly'
)

fig.show()

## **Insights**

O modelo acertou **98% de todas as previsões** (acurácia), consequentemente o recall também acompanhou esse valor, com **uma média 98% de acerto em todas as categorias** de Score de Crédito nas bases de Treinamento.

Analisando a Matriz de Confusão, podemos notar que o **modelo teve "maior dificuldade" em acertar a categória "Low"**, apontando 2 registros como "Average", e uma maior **facilidade de prever registros "High"**, apontando corretamente 83 de 84 registros.

# 4) Aplique o modelo aos dados de teste e realize a avaliação dos resultados, da mesma forma que fez acima. Não se esqueça de avaliar com as suas palavras e comparar o desempenho da base treino com a teste.

In [36]:
# Fazendo previsões nos dados de Teste
y_pred_test = naive_credit_score.predict(x_test)

# ACURÁCIA
test_accuracy = accuracy_score(y_test, y_pred_test)
print("Acurácia:", test_accuracy)

# RECALL
test_recall = recall_score(y_test, y_pred_test, average = 'macro')
print("Recall:", test_recall)

Acurácia: 0.975609756097561
Recall: 0.9444444444444445

In [37]:
# Matriz de Confusão
conf_matrix = confusion_matrix(y_test, y_pred_test)

# Definindo os nomes de classes
class_names = ['Low', 'Average', 'High']

# Matriz de Confusão
fig = ff.create_annotated_heatmap(
    z = conf_matrix,
    x = class_names,
    y = class_names,
    colorscale = 'Blues',
    showscale = True
)

# Estilizando
fig.update_layout(
    title = 'Matriz de Confusão',
    xaxis_title = 'Rótulos Previstos',
    yaxis_title = 'Rótulos Verdadeiros',
    font = dict(
        family = 'Arial',
        size = 12,
        color = 'black'
    ),
    template = 'plotly'
)

fig.show()

## **Insights**

O Modelo também apresentou um **desempenho excelente nos dados de Teste**, **acertando 97% de todas as previsões feitas** (acurácia) e um **acerto médio de 94% por categória** de Score de Crédito (recall)

Analisando a Matriz de Confusão, podemos notar que a "dificuldade" de acertar a categória "Low" apresentada nas bases de Treino também se manteve nas bases de Teste, apontando 1 registro "Low" como "Average". Novamente houve um destaque na categória "High", com o modelo acertando 100% de todos os 29 registros "High".

Com base nos dados de Teste, a príncipio podemos afirmar que o modelo conseguiu generalizar muito bem os dados de Treino e conseguiu apresentar uma ótima assertividade nos dados de Teste

# 5) Descreva com suas palavras o projeto desenvolvido nessa atividade e qual o nosso objetivo principal ao aplicarmos o algoritmo de naive bayes a base de crédito.
Utilize pelo menos 4 linhas.

Dica: Caso você ainda esteja tendo dificuldade em visualizar a aplicação dos projetos e objetivo, consulte seus tutores!

Realizamos um projeto com um modelo de aprendizagem supervisionado de classificação com o objetivo de **prever a classificação de Score de Crédito de clientes** a partir de variáveis como: idade, renda, nível de escolaridade, posse de imóvel, entre outras.

O algoritmo Naive Bayes foi aplicado porque o problema envolve a previsão de categorias (Low, Average e High) e não uma variável contínua, portanto, caracterizando uma tarefa de classificação. Além disso, as variáveis utilizadas possuem relativa independência entre si, o que favorece a aplicação do modelo.

Outra vantagem do Naive Bayes é sua capacidade de atualizar as probabilidades conforme novos registros são inseridos na base de dados, permitindo que o modelo refine suas previsões ao longo do tempo.